apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "example-service.fullname" . | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ include "example-service.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "example-service.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "example-service.name" . }}
    spec:
      containers:
        - name: example-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources: {{ toYaml .Values.resources | nindent 12 }}
